apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-k8-app
  labels:
    app: first-k8-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-k8-app
  template:
    metadata:
      labels:
        app: first-k8-app
    spec:
      containers:
        - name: first-docker
          image: higharc91/docker-travis-ci-example:latest
          ports:
            - containerPort: 80
